package com.admin.Util;

public class DatabaseConstants {
	public static final String CATAGORY_NAME = "CATAGORY_NAME";
	public static final String MANUFACTURER_PART = "MANUFACTURER_PART";
	public static final String SEMIKART_PART = "SEMIKART_PART";
	public static final String DATA_SHEET_URL = "DATA_SHEET_URL";
	public static final String DESCRIPTION = "DESCRIPTION";
	public static final String IS_NEW_PRODUCT = "IS_NEW_PRODUCT";
	public static final String IS_FEAUTURED_PRODUCT = "IS_FEAUTURED_PRODUCT";
	public static final String PRODUCT_STATUS = "PRODUCT_STATUS";
	public static final String MANUFACTURER_NAME = "MANUFACTURER_NAME";
	public static final String IMAGE_URL = "IMAGE_URL";
	public static final String PRODUCT_CATALOG_ID = "PRODUCT_CATALOG_ID";
	public static final String PRICE_TAG_ID="PRICE_TAG_ID";
	public static final String QUENTITY="QUENTITY";
	public static final String SALE_PRICE="SALE_PRICE";
	public static final String TAX="TAX";
	public static final String SKU="SKU";
	public static final String RETAIL_PRICE="RETAIL_PRICE";
	public static final String ROHAS="ROHAS";
	public static final String PRICE="PRICE";
	public static final String QUANTITY="QUANTITY";
	public static final String TOTAL_PRICE="TOTAL_PRICE";
	public static final String 	SEMICART_WISH_LIST_ID="SEMICART_WISH_LIST_ID";
	public static final String	MANUFACTURER_LOGO="MANUFACTURER_LOGO";
	public static final String CURRENCY_MARKUP = "CURRENCY_MARKUP";
	public static final String SUPPLIER_ID = "SUPPLIER_ID";
	public static final String VAT = "VAT";
	public static final String DUTY = "DUTY";
	public static final String HFI = "HFI";
	public static final String CATEGORY_ID = "CATEGORY_ID";
	public static final String SUPPLIER_PRICE_CONFIG_NO = "SUPPLIER_PRICE_CONFIG_NO";

	public static final String MAIN_CATAGORY_ID = "MAIN_CATAGORY_ID";
	public static final String MAIN_CATAGORY_NAME = "MAIN_CATAGORY_NAME";
	public static final String INCLUDE_IN_SUBMENU = "INCLUDE_IN_SUBMENU";
	public static final String MAIN_MENU = "MAIN_MENU";
	public static final String MAIN_SUB_CATEGORY_NAME = "MAIN_SUB_CATEGORY_NAME";

	public static final String STOCK = "STOCK";
	public static final String MINI = "MINI";
	public static final String MULT = "MULT";
	public static final String LEAD_TIME = "LEAD_TIME";
	public static final String SUPPLIER_NAME = "SUPPLIER_NAME";

	public static final String CUSTOMER_ADDRESS_ID = "CUSTOMER_ADDRESS_ID";
	public static final String ADDRESS_NAME = "ADDRESS_NAME";
	public static final String ADDRESS_ID = "ADDRESS_ID";
	public static final String ADDRESS_LINE1 = "ADDRESS_LINE1";
	public static final String ADDRESS_LINE2 = "ADDRESS_LINE2";
	public static final String ADDRESS_LINE3 = "ADDRESS_LINE3";
	public static final String CITY = "CITY";
	public static final String COMPANY_NAME = "COMPANY_NAME";
	public static final String COUNTY = "COUNTY";
	public static final String FIRST_NAME = "FIRST_NAME";
	public static final String FULL_NAME = "FULL_NAME";
	public static final String POSTAL_CODE = "POSTAL_CODE";
	public static final String PHONE_NUMBER = "PHONE_NUMBER";
	public static final String IS_DEFAULT = "IS_DEFAULT";
	public static final String SHIPPING_COST = "SHIPPING_COST";
	public static final String HDFC_PAYMENT_GATEWAY_TESTING_KEY = "ZrZMUV";
	public static final String HDFC_PAYMENT_GATEWAY_TESTING_SALT = "J4Otw4RV";
	public static final String HDFC_PAYMENT_GATEWAY_TESTING_URL = "https://test.payu.in/_payment";

	public static final String TRANSACTION_STATUS_PENDING = "PENDING";

	public static final String ORDER_STATUS = "1";
	public static final String CURRENT_DATE = "CURRENT_DATE";

	public static final String SEARCH_FEAUTURED_PRODUCT = "SELECT PC.PRODUCT_CATALOG_ID, PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.IS_NEW_PRODUCT,PC.IS_FEAUTURED_PRODUCT,PC.PRODUCT_STATUS,"
			+ " MAF.MANUFACTURER_NAME,CAT.CATAGORY_NAME FROM PRODUCT_CATALOG PC INNER JOIN MANUFACTURER MAF ON MAF.MANUFACTURER_ID=PC.MANUFACTURER_ID "
			+ " INNER JOIN CATEGORY CAT ON CAT.CATAGORY_ID=PC.CATAGORY_ID WHERE IS_FEAUTURED_PRODUCT='Y'";

	public static final String GET_DROP_DOWN_FOR_PRODUCT_LIST = "SELECT * FROM main_category where INCLUDE_IN_SUBMENU='Y' AND MAIN_MENU=? ";
	public static final String GET_DROP_DOWN_FOR_NEW_PRODUCT_LIST = "SELECT PC.PRODUCT_CATALOG_ID, PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.IS_NEW_PRODUCT,PC.IS_FEAUTURED_PRODUCT,PC.PRODUCT_STATUS,"
			+ " MAF.MANUFACTURER_NAME,CAT.CATAGORY_NAME FROM PRODUCT_CATALOG PC INNER JOIN MANUFACTURER MAF ON MAF.MANUFACTURER_ID=PC.MANUFACTURER_ID "
			+ " INNER JOIN CATEGORY CAT ON CAT.CATAGORY_ID=PC.CATAGORY_ID WHERE IS_NEW_PRODUCT='Y'";

	public static final String GET_HOT_DEAL_PRODUCT_LIST = "SELECT MSC.MAIN_SUB_CATEGORY_NAME,CA.CATAGORY_NAME,PC.PRODUCT_CATALOG_ID,PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.PRODUCT_NAME,SC.STOCK,SC.MINI,SC.MULT,SC.LEAD_TIME,MAN.MANUFACTURER_NAME FROM product_catalog PC INNER JOIN category CA"
			+ " ON PC.CATAGORY_ID=CA.CATAGORY_ID INNER JOIN main_sub_category MSC ON MSC.MAIN_SUB_CATEGORY_ID=CA.MAIN_SUB_CATEGORY_ID INNER JOIN main_category MC ON MC.MAIN_CATAGORY_ID=MSC.MAIN_CATAGORY_ID LEFT JOIN manufacturer MAN "
			+ " ON MAN.MANUFACTURER_ID=PC.MANUFACTURER_ID LEFT JOIN supplier_catalog SC ON SC.PRODUCT_CATALOG_ID=PC.PRODUCT_CATALOG_ID WHERE PC.HOT_DEAL='Y'";

	public static final String GET_NEWEST_PRODUCT_LIST = "SELECT MSC.MAIN_SUB_CATEGORY_NAME,CA.CATAGORY_NAME,PC.PRODUCT_CATALOG_ID,PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.PRODUCT_NAME,SC.STOCK,SC.MINI,SC.MULT,SC.LEAD_TIME,MAN.MANUFACTURER_NAME FROM product_catalog PC INNER JOIN category CA"
			+ " ON PC.CATAGORY_ID=CA.CATAGORY_ID INNER JOIN main_sub_category MSC ON MSC.MAIN_SUB_CATEGORY_ID=CA.MAIN_SUB_CATEGORY_ID INNER JOIN main_category MC ON MC.MAIN_CATAGORY_ID=MSC.MAIN_CATAGORY_ID LEFT JOIN manufacturer MAN "
			+ " ON MAN.MANUFACTURER_ID=PC.MANUFACTURER_ID LEFT JOIN supplier_catalog SC ON SC.PRODUCT_CATALOG_ID=PC.PRODUCT_CATALOG_ID WHERE PC.IS_NEW_PRODUCT='Y'";

	public static final String GET_POPULAR_PRODUCT_LIST = "SELECT MSC.MAIN_SUB_CATEGORY_NAME,CA.CATAGORY_NAME,PC.PRODUCT_CATALOG_ID,PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.PRODUCT_NAME,SC.STOCK,SC.MINI,SC.MULT,SC.LEAD_TIME,MAN.MANUFACTURER_NAME FROM product_catalog PC INNER JOIN category CA"
			+ " ON PC.CATAGORY_ID=CA.CATAGORY_ID INNER JOIN main_sub_category MSC ON MSC.MAIN_SUB_CATEGORY_ID=CA.MAIN_SUB_CATEGORY_ID INNER JOIN main_category MC ON MC.MAIN_CATAGORY_ID=MSC.MAIN_CATAGORY_ID LEFT JOIN manufacturer MAN "
			+ " ON MAN.MANUFACTURER_ID=PC.MANUFACTURER_ID LEFT JOIN supplier_catalog SC ON SC.PRODUCT_CATALOG_ID=PC.PRODUCT_CATALOG_ID WHERE PC.POPULAR='Y'";

	public static final String PRODUCT_SEARCH_FOR_VIEW = "SELECT MAN.IMAGE_URL AS MANUFACTURER_LOGO,CA.CATAGORY_NAME,PC.PRODUCT_CATALOG_ID,PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DATA_SHEET_URL,PC.IMAGE_URL,PC.DESCRIPTION,PC.PRODUCT_NAME,MAN.MANUFACTURER_NAME FROM product_catalog PC INNER JOIN category CA"
			+ " ON PC.CATAGORY_ID=CA.CATAGORY_ID INNER JOIN main_sub_category MSC ON MSC.MAIN_SUB_CATEGORY_ID=CA.MAIN_SUB_CATEGORY_ID INNER JOIN main_category MC ON MC.MAIN_CATAGORY_ID=MSC.MAIN_CATAGORY_ID LEFT JOIN manufacturer MAN "
			+ " ON MAN.MANUFACTURER_ID=PC.MANUFACTURER_ID";
	public static final String PRODUCT_SEARCH_SUPPLIER_DETAILS = " SELECT SPC.VAT,SC.SUPPLIER_CATALOG_ID,SC.SUPPLIER_ID,SC.STOCK,SC.MINI,SC.MULT,SC.LEAD_TIME,SUP.SUPPLIER_NAME,SUP.SUPPLIER_ID FROM SUPPLIER_CATALOG SC  INNER JOIN SUPPLIER SUP ON SUP.SUPPLIER_ID=SC.SUPPLIER_ID INNER JOIN product_catalog PC on pc.PRODUCT_CATALOG_ID=SC.PRODUCT_CATALOG_ID LEFT JOIN supplier_price_config SPC ON SPC.SUPPLIER_ID=SC.SUPPLIER_ID AND pc.CATAGORY_ID=SPC.CATEGORY_ID WHERE SC.PRODUCT_CATALOG_ID=?";
	public static final String PRODUCT_SEARCH_PRICE_DETAILS=" SELECT PT.PRICE_TAG_ID,PT.PRODUCT_CATALOG_ID,PT.SUPPLIER_ID,PT.QUENTITY,PT.SALE_PRICE,PT.TAX,PT.SKU,PT.RETAIL_PRICE FROM PRICE_TAG PT WHERE PT.PRODUCT_CATALOG_ID=? AND PT.SUPPLIER_ID=? ";
	

	public static final String PRODUCT_SEARCH_CATEGORY_LIST = "SELECT DISTINCT CA.CATAGORY_NAME FROM CATEGORY CA INNER JOIN MAIN_SUB_CATEGORY MSC ON MSC.MAIN_SUB_CATEGORY_ID=CA.MAIN_SUB_CATEGORY_ID INNER JOIN MAIN_CATEGORY MC ON MC.MAIN_CATAGORY_ID=MSC.MAIN_CATAGORY_ID ";

	public static final String GET_CUSTOMER_ADDRESS_DETAILS = "select BA.IS_DEFAULT,BCA.CUSTOMER_ADDRESS_ID,BCA.ADDRESS_NAME,BCA.ADDRESS_ID,BA.ADDRESS_LINE1,BA.ADDRESS_LINE2,BA.ADDRESS_LINE3,BA.CITY,BA.COMPANY_NAME,BA.COUNTY,BA.FIRST_NAME,BA.FULL_NAME,BA.POSTAL_CODE, BP.PHONE_NUMBER,PC.rates as SHIPPING_COST from  blc_customer_address BCA INNER JOIN blc_address BA ON BA.ADDRESS_ID=BCA.ADDRESS_ID INNER JOIN blc_phone BP ON BP.PHONE_ID= BA.PHONE_PRIMARY_ID inner join pincode PC on PC.pincode=ba.postal_code WHERE BCA.CUSTOMER_ID=?";
	public static final String DELETE_CUSTOMER_ADDRESS = "DELETE FROM blc_customer_address where customer_address_id=?";
	public static final String GET_CURRENT_DATE = "select DATE_FORMAT(NOW(),'%d-%m-%Y')";

	public static final String GET_WISHLIST_DETAILS = "SELECT PC.PRODUCT_CATALOG_ID,SUP.SUPPLIER_ID,SWL.SEMICART_WISH_LIST_ID, SUP.SUPPLIER_NAME,PC.MANUFACTURER_PART,PC.SEMIKART_PART,PC.DESCRIPTION,PC.ROHAS,PT.PRICE,SWL.quantity,(PT.PRICE*SWL.quantity) AS TOTAL_PRICE,SC.STOCK,SPC.VAT FROM PRODUCT_CATALOG pc inner join PRICE_TAG PT on pc.PRODUCT_CATALOG_ID=PT.PRODUCT_CATALOG_ID INNER JOIN semikart_wish_list SWL on swl.PRODUCT_CATALOG_ID=pc.PRODUCT_CATALOG_ID  INNER JOIN  SUPPLIER_CATALOG SC ON SC.PRODUCT_CATALOG_ID=SWL.PRODUCT_CATALOG_ID AND SC.SUPPLIER_ID=SWL.SUPPLIER_ID INNER JOIN SUPPLIER SUP ON SUP.SUPPLIER_ID=SWL.SUPPLIER_ID LEFT JOIN SUPPLIER_PRICE_CONFIG SPC ON SPC.SUPPLIER_ID=SWL.SUPPLIER_ID AND SPC.CATEGORY_ID=PC.CATAGORY_ID where SWL.CUSTOMER_ID=?  AND (swl.quantity-PT.quentity)>0 AND SWL.STATUS='ADDED TO WISHLIST'";
	
	
	
	// ///////////////MOUSER API
	public static final String GET_MANUFACTURER_ID = "SELECT MANUFACTURER_ID FROM manufacturer";
	public static final String GET_MAIN_CATEGORY_ID = "SELECT MAIN_CATAGORY_ID FROM main_category ";
	public static final String GET_MAIN_SUB_CATEGORY_ID = "SELECT MAIN_SUB_CATEGORY_ID FROM main_sub_category ";
	public static final String GET_CATEGORY_ID = "SELECT CATAGORY_ID FROM category ";
	public static final String GET_PRODUCT_CATALOG_ID = "SELECT PRODUCT_CATALOG_ID FROM product_catalog ";
	public static final String GET_SUPPLIER_ID = "SELECT supplier_id FROM supplier ";
	public static final String GET_SUPPLIER_CATALOG_ID = "SELECT SUPPLIER_CATALOG_ID FROM supplier_catalog where PRODUCT_CATALOG_ID=? AND SUPPLIER_ID=?";

	public static final String GET_SUPPLIER_PRICE_CONFIG_ID = "SELECT SUPPLIER_PRICE_CONFIG_NO FROM supplier_price_config  where SUPPLIER_ID=? AND CATEGORY_ID=?";
	public static final String GET_PRICE_TAG_ID = "SELECT PRICE_TAG_ID FROM price_tag  where PRODUCT_CATALOG_ID=? AND SUPPLIER_ID=? AND QUENTITY=?";
	public static final String GET_SUPPLIER_PRICE_CONFIG = "SELECT * FROM supplier_price_config  where SUPPLIER_PRICE_CONFIG_NO=?";
	// /////////////////////////END MOUSERE
}
